package com.sda.app.entity;

public enum Category {
    PASSIVE_COMPONENTS,
    DISCRET_SEMICONDUCTORS,
    PCBS,
    CIRCUIT_PROTECTION,
    CONECTORS,
    TEELCOMUNICATION,
    AUDIO,
    SENSORS,
    IOT,
    RESISTORS,
    CAPACITORS,
    INDUCTORS,
    TRANSISTORS,
    DIODS,
    RECTIFIERS,
    DSM,
    CERAMIC_PBC,
    ALUMINUM_PCB,
    PCBA,
    THYRISTORS,
    CERAMICPCB, ALUMINUMPCB,
    FPC, RIGIDPCB, FUSES, VARISTORS, TVS1, TVS2, BREAKERS, TVS3, TVS4, TVS5,
    OTHER_C_P, GDT, PTC, THERMISTORS, USB_CONECTOR, HEADERS, OTHER_CONNECTORS,
    FIBER_OPTIC_C, CONNCETORS, TERMINAL_BLOCKS,BT_MODULE


}
